server:
    port: 9000
eureka:
   client:
      service-url:
       defaultZone: http://localhost:8761/eureka/

spring:
 application:
  name: APIGateWayForService
 cloud:
    gateway:
      routes:
        - id: WeatherApplicationAdmin
          uri: http://localhost:9090/
          predicates:
            - Path=/api/Weather/**
        - id: WeatherApplicationUser
          uri: http://localhost:9091/
          predicates:
            - Path=/api/Weather/**    
        - id: WeatherApp_JWT_Service
          uri: http://localhost:9093/
          predicates:
            - Path=/api/**  
