jwt:
  secret: secrectkey123

server:
    port: 9093         
    
    
spring:
    application:
           name: WeatherApp_JWT_Service
    data:
        mongodb:
             uri: mongodb+srv://Isha-Ganar:mydatabase@cluster0.jhs8v.mongodb.net/WeatherDB?retryWrites=true&w=majority
eureka:
     client:
          service-url:
                   defaultZone: http://localhost:8761/eureka/          
                          
logging:
  file: 
    path: /my-logs/app.log
    name: log.txt  
    
data:
   exception:
          incmsg: Invalid Credentials!!
            